[package]
name = "clean_read_v2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kuchiki = "*"
reqwest = { version = "*", features = [
    "blocking",
    "gzip",
    "deflate",
    "cookies",
    "rustls-tls",
], default-features = false }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
toml = "0.5.8"
actix-web = "4.0.1"
hex = "0.4.3"
sha2 = "0.10.2"
anyhow = "1.0.42"
base64 = "0.13.0"
dashmap = "5.2.0"
once_cell = "1.8.0"
html-escape = "0.2.9"
regex = "1.5.4"

# Image related

ravif = { git = "https://github.com/kornelski/cavif-rs" }
rayon = "1.5.1"
rgb = "0.8.29"
imgref = "1.9.1"
image = "0.24.1"
