[package]
name = "clean_read_v2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kuchiki = "*"
reqwest = { version = "*", features = [
    "blocking",
    "gzip",
    "deflate",
    "cookies",
] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
actix-web = "3.3.2"
hex = "0.4.3"
sha2 = "0.9.5"
anyhow = "1.0.42"
base64 = "0.13.0"
dashmap = "4.0.2"
once_cell = "1.8.0"
html-escape = "0.2.9"
regex = "1.5.4"
