enable_debug_text_element = false
enable_cache = true
cache_folder = "cache"
text_element_debug_file = "target/text_element.txt"
database_file = "template/db.json"
address = "127.0.0.1:8080"
bench_mode = true
